name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.15
        os:
          - macos
          - ubuntu
        goarch:
          - amd64
          - arm
        exclude:
          - os: macos
            goarch: arm

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Restore Chache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
        go get github.com/golang/protobuf/protoc-gen-go

    - name: Generate code with gRPC
      run: make generate

    - name: Build
      run: go build
      env:
          GOARCH: ${{ matrix.goarch }}

    - name: Upload artifact to share url with other jobs
      uses: actions/upload-artifact@v2
      with:
        path: thermostat*
